name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at every 12AM UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_MESSAGE: Updated the Readme
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          LOCALE: "ko"
          SHOW_TITLE: true
          SHOW_TOTAL: true
          SHOW_LINES_OF_CODE: true
          SHOW_TIME: false
          SHOW_PROFILE_VIEWS: false
          SHOW_DAYS_OF_WEEK: false
          SHOW_SHORT_INFO: false
          SHOW_LOC_CHART: false
          SHOW_PROJECTS: false
          SHOW_LANGUAGE_PER_REPO: false
